/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alberca;

import Consultas.maestros;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Choche
 */
public class agregarprofesor extends javax.swing.JFrame {

    /** Creates new form agregarprofesor */
    public agregarprofesor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre1 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(703, 360));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lblnombre1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblnombre1.setForeground(new java.awt.Color(204, 204, 204));
        lblnombre1.setText("Apellidos:");
        getContentPane().add(lblnombre1);
        lblnombre1.setBounds(70, 180, 140, 31);

        txtapellidos.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtapellidos);
        txtapellidos.setBounds(200, 170, 290, 40);

        lblnombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(204, 204, 204));
        lblnombre.setText("Nombre:");
        getContentPane().add(lblnombre);
        lblnombre.setBounds(70, 130, 120, 31);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar profesor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 20, 310, 50);

        txtnombre.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre);
        txtnombre.setBounds(200, 120, 290, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/logo2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 0, 90, 130);

        btncancelar.setBackground(new java.awt.Color(255, 0, 0));
        btncancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar);
        btncancelar.setBounds(400, 250, 140, 50);

        btnguardar.setBackground(new java.awt.Color(51, 255, 0));
        btnguardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(140, 250, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/azul claro 1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if(txtnombre.getText().equals("")|txtapellidos.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "<html><span style=\"font-size:2em\">Ingresa los campos correspondientes</span></html>",
                        "Éxito",JOptionPane.WARNING_MESSAGE);
        }else{
            maestros ma=new maestros();
            ma.insermaestros(txtnombre.getText(), txtapellidos.getText());
            txtnombre.setText("");
            txtapellidos.setText("");
            
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
         if (txtnombre.getText().length() == 34) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())
                & !(evt.getKeyChar() == KeyEvent.VK_SPACE)
                & !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
//      lblErrorLetra.setText("Escribe solo letras");
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
         if (txtapellidos.getText().length() == 34) {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar())
                & !(evt.getKeyChar() == KeyEvent.VK_SPACE)
                & !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
//      lblErrorLetra.setText("Escribe solo letras");
        }
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarprofesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarprofesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarprofesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarprofesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarprofesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

}
