/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alberca;

import Consultas.Camara1;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Choche
 */
public class Camara extends javax.swing.JFrame {

    /**
     * Creates new form Camara
     */
    //Camara
    Inscripciones ins = new Inscripciones();
    public int idusuario;
    int largocamara = 230;
    int anchocamara = 210;
    Dimension dimension = new Dimension(largocamara, anchocamara);
    Dimension dimension1 = WebcamResolution.VGA.getSize();
    Webcam webcam = Webcam.getDefault();
    WebcamPanel webcamPanel = new WebcamPanel(webcam, dimension, false);
    BufferedImage ruta;
    int contador = 0;
    Icon iconofoto;

    //Fin camara
    public Camara() {
        initComponents();
        this.setLocationRelativeTo(null);
        webcam.setViewSize(dimension1);
        webcamPanel.setFillArea(true);
        jpcamara.setLayout(new FlowLayout());
        jpcamara.add(webcamPanel);

        lblnombre.setText(webcam.toString());

        btntomarfoto.setEnabled(false);
        btnguardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        btniniciar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btntomarfoto = new javax.swing.JButton();
        jpcamara = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(647, 390));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Atrás azul.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(22, 12, 50, 40);
        getContentPane().add(lblfoto);
        lblfoto.setBounds(440, 30, 170, 170);

        btniniciar.setBackground(new java.awt.Color(0, 153, 204));
        btniniciar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btniniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Prender.png"))); // NOI18N
        btniniciar.setText("Iniciar");
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btniniciar);
        btniniciar.setBounds(20, 90, 140, 50);

        btnguardar.setBackground(new java.awt.Color(51, 255, 0));
        btnguardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Guardar 2.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(460, 200, 140, 50);

        btntomarfoto.setBackground(new java.awt.Color(0, 153, 204));
        btntomarfoto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btntomarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cámara.png"))); // NOI18N
        btntomarfoto.setText("Tomar foto");
        btntomarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntomarfotoActionPerformed(evt);
            }
        });
        getContentPane().add(btntomarfoto);
        btntomarfoto.setBounds(220, 270, 180, 50);

        jpcamara.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpcamaraLayout = new javax.swing.GroupLayout(jpcamara);
        jpcamara.setLayout(jpcamaraLayout);
        jpcamaraLayout.setHorizontalGroup(
            jpcamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jpcamaraLayout.setVerticalGroup(
            jpcamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jpcamara);
        jpcamara.setBounds(190, 30, 240, 220);

        lblnombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblnombre);
        lblnombre.setBounds(150, 320, 310, 30);

        lblimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/azul claro 1.jpg"))); // NOI18N
        getContentPane().add(lblimagen);
        lblimagen.setBounds(0, 0, 1280, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        webcamPanel.stop();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
        btntomarfoto.setEnabled(true);
        Thread hilo = new Thread() {
            @Override
            public void run() {
                webcamPanel.start();
            }
        };
        hilo.setDaemon(true);
        hilo.start();
        btniniciar.setEnabled(false);

    }//GEN-LAST:event_btniniciarActionPerformed

    private void btntomarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntomarfotoActionPerformed
        btnguardar.setEnabled(true);
        ImageIcon foto;
        foto = new ImageIcon(webcam.getImage());
        iconofoto = new ImageIcon(foto.getImage().getScaledInstance(lblfoto.getWidth(),
                lblfoto.getHeight(), Image.SCALE_SMOOTH));
        lblfoto.setIcon(iconofoto);

        ruta = webcam.getImage();

    }//GEN-LAST:event_btntomarfotoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(this, "¿Deseas guardar la foto?", "Pregunta", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (pregunta == 0) {
//            Inscripciones ins= new Inscripciones();
//            
//            ins.lblfotousuario.setIcon(iconofoto);
            webcamPanel.stop();
//            this.setVisible(false);
//            String imagensave="C:\\Users\\Choche\\Documents\\Fotos del usuario\\foto"+idusuario+".jpg";
            String imagensave = "C:\\Users\\Lu\\Desktop\\Fotos del usuario\\foto" + idusuario + ".jpg";
            File salidaimagen = new File(imagensave);
            Camara1 cama = new Camara1();

            try {
                ImageIO.write(ruta, "jpg", salidaimagen);
                System.out.println("Foto guardada: " + salidaimagen.getAbsolutePath());
                cama.ponerfoto(idusuario, imagensave);
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {

        }
//        webcamPanel.stop();

    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btniniciar;
    private javax.swing.JButton btntomarfoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jpcamara;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables
}
